spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/fish_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8083

# JWT secret key (Base64-encoded)
app.jwt.secret=Zmlyc2gtYnJlZWRpbmctc3lzdGVtLXN1cGVyLXNlY3VyZS1qd3Qta2V5LWNoYW5nZS1pbi1wcm9k